name: 'model 01000'
data_path: 'data/ELISA_merged.csv'
attributes: ['Acceleration', 'CO2', 'Charginginfrastructure', 'Chargingspeed', 'Homechargeravailability', 'Homedistnearestcharger', 'Operationcost', 'Purchaseprice', 'Range', 'Size', 'Yearlycost']
characteristics: ['gender']
nested: False
# test_size: 0.25