name: 'model_00000'
data_path: 'data/ELISA_merged.csv'
attributes: ['Acceleration', 'CO2', 'Charginginfrastructure', 'Chargingspeed', 'Homechargeravailability', 'Homedistnearestcharger', 'Operationcost', 'Purchaseprice', 'Range', 'Size', 'Yearlycost']
characteristics: []
# scenario: {}
scenario: {'Purchaseprice': 0.1}
nested: False
estimation: False
# test_size: 0.25

